FROM docker.io/library/archlinux:latest

LABEL maintainer="thorstenrie <https://github.com/thorstenrie/ts-seedbox>"

ARG UGID=667

RUN groupadd -g $UGID rtorrent && \
     useradd -r -m -l -u $UGID -g rtorrent rtorrent && \
     pacman -Syu --noconfirm && \
     pacman -S --noconfirm rtorrent bind && \
     mkdir -p /home/rtorrent/rtorrent/config.d && \
     mkdir /home/rtorrent/rtorrent/.session && \
     mkdir /home/rtorrent/rtorrent/download && \
     mkdir /home/rtorrent/rtorrent/watch && \
     chown -R rtorrent:rtorrent /home/rtorrent/rtorrent

COPY --chown=rtorrent:rtorrent config.d/ /home/rtorrent/rtorrent/config.d/
COPY --chown=rtorrent:rtorrent .rtorrent.rc /home/rtorrent/

EXPOSE 50000
EXPOSE 6881
EXPOSE 6881/udp

USER rtorrent

CMD ["rtorrent"]
